name: Deployment pipeline

on:
  push:
    branches:
      - master  
  pull_request:
      branches: [master]
      types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  deploy_for_production:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ci-cd-bloglist-app"
          heroku_email: ashikreji27@gmail.com
          justlogin: true
  tag_release:
    needs: [deploy_for_production]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip')}}
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  conclusion:
    needs: [tag_release]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps: 
      - name: Test success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with: 
          username: MyGithubBot
          color: '#00FF00'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: 'to something something by me '
          footer: 'Severity: Informational'
          text: A new version of Pokedex is deployed!!!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test failed
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with: 
          username: MyGithubBot
          color: '#ff0000'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: 'to something something by me '
          footer: 'Severity: Error'
          text: Build failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info

          


