name: Deployment pipeline

on:
  push:
    branches:
      - master  
  pull_request:
      branches: [master]
      types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
  deploy_for_production:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: nameless-depths-92509
          heroku_email: ashikreji27@gmail.com
          justlogin: true
  tag_release:
    needs: [deploy_for_production]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push'}}
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          


